name = "mcp-chat-client"
compatibility_date = "2023-12-01"
main = "worker.js"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "module"
dir = "."
main = "./worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
NODE_ENV = "production" 