name = "mcp-chat-client"
compatibility_date = "2023-12-01"
main = "server.js"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "modules"
dir = "."
main = "./server.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production]
workers_dev = true 